name: Parallel jobs pipeline

on:
  pull_request:
    branches: [master]
    types: ['opened', 'edited', 'synchronize']

jobs: 
  cancel_previous_workflows:
    name: Cancel previous redundant workflows
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  
  # This is a step only to cache dependencies for next steps (dont save a lot of time, its not really needed)
  install_dependencies: 
    name: 'Install and cache dependences'
    runs-on: ubuntu-20.04
    steps:  
      - name: Get code
        uses: actions/checkout@v4
      - name: Config node
        uses: actions/setup-node@v4
        with:
          cache: 'npm' # Caches dependencies so it does not need to install every time
          node-version: 20
      - name: Install dependencies
        run: npm ci

  
  linter:
    needs: [install_dependencies]
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Config node
        uses: actions/setup-node@v4
        with:
          cache: 'npm' # Caches dependencies so it does not need to install every time
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
  
  build:
    needs: [install_dependencies]
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Config node
        uses: actions/setup-node@v4
        with:
          cache: 'npm' # Caches dependencies so it does not need to install every time
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      # This will upload the artifact that tests will use
      - name: Upload artifact to use in "tests" job
        uses: actions/upload-artifact@v4
        with:
          name: build artifact
          path: build

  # Tests depend on build. We use the artifact from above
  tests:
    needs: [linter, build] # This waits for this 2 jobs to finish before executing
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Config node
        uses: actions/setup-node@v4
        with:
          cache: 'npm' # Caches dependencies so it does not need to install every time
          node-version: 20
      # We use the same ghaction but with "download" instead of upload
      - name: Download artifact from "build" job.
        uses: actions/download-artifact@v4
        with:
          name: build artifact # must match with build artifact name
          path: build
      - name: Run tests
        run: npm run test