name: Beerfox pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  linter:
    name: 'Lint and test'
    runs-on: ubuntu-18.04
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Config node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: linter
        run: npm run lint
      - name: test
        run: npm run test

  