name: Beerfox pipeline

on:
  pull_request:
    branches: [adasd]
    types: ['opened', 'edited', 'synchronize']


jobs:
  linter:
    name: 'Lint and test'
    runs-on: ubuntu-20.04
    steps:
      # IMPORTANT: this is to cancel previous workflows and avoid deploying outdated stuff
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}
      - name: Get code
        uses: actions/checkout@v4
      - name: Config node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: linter
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      # Here we could add an action to deploy

  